### PR TITLE
Make GitHub.auth non-nullable

### PR DESCRIPTION
**Pull request by CaseyHillers**
For the most part, this is already non-nullable.

See https://github.com/flutter/flutter/issues/129134 - This should help with debugging why our server is getting a null auth state.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
FYI looks like some recent Dart changes around sealable classes are causing some CI failures, unrelated to this change. I can send a fix tonight.

**Comment by kevmoo** [comment]
We'll want a changelog entry here, right?

**Comment by CaseyHillers** [comment]
> We'll want a changelog entry here, right?

Changelog entries are generated by the GitHub action

**Review by kevmoo — APPROVED** [review]

**Comment by CaseyHillers** [comment]
@robbecker-wf can you help release this? \cc @ricardoamador

**Comment by robrbecker** [comment]
Released in version 9.15.0 https://github.com/SpinlockLabs/github.dart/releases/tag/9.15.0

**Comment by Hixie** [comment]
I don't mind making this non-nullable, but can we restore making it mutable? GitHub credentials regularly need to be refreshed and having to recreate a whole new `GitHub` object each time is more annoying that just giving the existing object a new authentication token.

**Comment by CaseyHillers** [comment]
> I don't mind making this non-nullable, but can we restore making it mutable?

Out of curiosity, do you have sample code I could take a look at? This seems like a fair request, but I was under the impression most callers will recreate the entire client instead of re-minting the auth.

**Comment by Hixie** [comment]
https://github.com/Hixie/cocoon/blob/9b487e12dab09c2eb396ce9aa9b5ee4a76991756/triage_bot/lib/engine.dart#L1147

**Pull request merged**
