### PR TITLE
Nullable hasPages

### PR DESCRIPTION
**Pull request by johnpryan**
This will throw an exception when calling
`GitHub().activity.listEventsPerformedByUser(username)`

### CODE REVIEW

**Review by robrbecker — APPROVED** [review]
@johnpryan Thanks!

**Comment by robrbecker** [comment]
Do you need a nullsafe.1 release with this in it?

**Comment by johnpryan** [comment]
That would be great, if you don't mind!

**Comment by robrbecker** [comment]
ok, I had some other adjustments to land in there too. Give https://pub.dev/packages/github/versions/8.0.0-nullsafe.1 a try.

**Pull request merged**
