### PR TITLE
Run format and analyze on presubmit/postsubmit

### PR DESCRIPTION
**Pull request by CaseyHillers**
I'm working on another PR, and noticed that all the tests that were passing or failing.

- Created github action for presubmit + postsubmit (run format and analyze)
  - Fix some lints, and generate mocks for null safety
- Created an integration test directory (this will require generating a secret to run against the github api)
- Disabled unit tests and integration tests until they can be fixed (hopefully we can parallelize fixing the tests)

### CODE REVIEW

**Comment by CaseyHillers** [comment]
\cc @kevmoo @robbecker-wf FYI - I'll try working on this, but I won't have much time next week to fix this. I'm going to rollback my package to 8.2.1. The tests are all failing even though the github check shows it as green

**Comment by kevmoo** [comment]
Cool! Glad someone is looking at it...

**Comment by robrbecker** [comment]
When I inherited this project I was unsure about the state of the tests and was warned that some of them ran on live github repos. I haven't ever gotten around to revamping the tests :shame:
I was hoping to use the same testing setup as whatever mock service gets stood up in the octokit repo(s) https://github.com/octokit

**Comment by CaseyHillers** [comment]
> When I inherited this project I was unsure about the state of the tests and was warned that some of them ran on live github repos. I haven't ever gotten around to revamping the tests :shame:
I was hoping to use the same testing setup as whatever mock service gets stood up in the octokit repo(s) https://github.com/octokit

I'll have to take a look! I think it's reasonable to get the integration tests working, but I'm not familiar with what octokit is doing

**Comment by CaseyHillers** [comment]
@robrbecker I simplified this to just enable format and analyze to start screening PRs

**Pull request merged**
