### PR TITLE
Fix GitHubFile.text decoding

### PR DESCRIPTION
**Pull request by kevmoo**
And prepare for 6.0.2 release

### CODE REVIEW

**Comment by robbecker-wf** [comment]
Interesting! Reviewing now...

**Comment by robbecker-wf** [comment]
I'm having trouble understanding where this regression was introduced. Merging and releasing the fix, but would love to understand what caused this.

**Comment by kevmoo** [comment]
> I'm having trouble understanding where this regression was introduced. Merging and releasing the fix, but would love to understand what caused this.

https://github.com/SpinlockLabs/github.dart/commit/a8c568e8ac1bb3479f9cbbd6d47c84cca2251428#diff-c4c617085801d90bf4257566f4722095L66-L68

Oops!

**Comment by robrbecker** [comment]
Oh, yeah, that's it alright.

**Pull request merged**
