### PR TITLE
require dart 3.0; update to the latest package:lints

### PR DESCRIPTION
**Pull request by devoncarew**
- require Dart 3.0
- update to the latest `package:lints`
- address new lints (and two existing lint issues, which were causing red bots)

### CODE REVIEW

**Comment by devoncarew** [comment]
This should address the bot failures seen in https://github.com/SpinlockLabs/github.dart/pull/398.

**Comment by devoncarew** [comment]
@CaseyHillers - can you review this?

**Review by CaseyHillers — COMMENTED** [review]
Thanks for the change! Before I can merge it, can you update the pubspec and the CHANGELOG?

**Comment by devoncarew** [comment]
> Thanks for the change! Before I can merge it, can you update the pubspec and the CHANGELOG?

yup - done

**Review by CaseyHillers — APPROVED** [review]

**Pull request merged**
